name: Release CrMenu

on:
  release:
    types: [published]
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn -B -DskipTests package

      - name: Upload JAR to existing release
        if: github.event_name == 'release'
        uses: softprops/action-gh-release@v1
        with:
          files: |
            target/CrMenu-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create release and upload JAR on tag
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref_name }}
          name: CrMenu ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            target/CrMenu-*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}